//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetAdopt
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cat
    {
        public int CatId { get; set; }
        public string Name { get; set; }
        public byte[] Image { get; set; }
        public string NeededHabitat { get; set; }
        public string NeededFood { get; set; }
        public Nullable<int> Age { get; set; }
        public string Gender { get; set; }
        public bool RecentCheckup { get; set; }
        public string About { get; set; }
        public string UserId { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
